# consistency of self calls
We are trying to see how reliably self echoes are heard and how consistent they are in the information they provide as oppposed to information coming from other direct calls/ echeos from their direct calls

Let us first load the data.

In [16]:
import sys
import os 
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
import itertools
import pickle
from mpl_toolkits.axes_grid1 import make_axes_locatable
os.chdir("/home/adityamoger/Documents/GitHub/dynamic_model_of_cocktail_party_nightmare/")

sys.path.append("./exploratory_analysis/")
sys.path.append("./dynamic_model/")

from supporting_files.read_simulation_output import read_data_per_simulation_per_bat
from supporting_files.utilities import make_dir

import bisect
import pandas as pd
plt.style.use("dark_background")

In [17]:
def make_ordered_lists_of_params(array_of_parameter_lists):
    product_of_lists = list(itertools.product(*array_of_parameter_lists))
    return product_of_lists

def reformat_matrices(nan_matrix, track_unique_objects):
    
    nan_matrix = nan_matrix.T
    
    sorting_indices = np.argsort(track_unique_objects)
    nan_matrix = nan_matrix[sorting_indices]
    track_unique_objects = np.array(track_unique_objects)[sorting_indices]
    
    # nan_matrix = nan_matrix[:, ~np.isnan(nan_matrix).all(0)]
    masked_array = np.ma.array(nan_matrix, mask=np.isnan(nan_matrix))
    
    return nan_matrix, track_unique_objects, masked_array

In [18]:
TEMPORAL_MASKING_DIR = "./JammingExperiment2/Data/InputData/temporal_masking_fn.csv"
DIRECTORY = f"./JammingExperiment2/Data/IntermediateData/debug7/"
DIRECTORY_STORE_PLOTS = "./JammingExperiment2/Output/DataAppendixOutput"

In [19]:
dictionary_to_store_all_sounds = {}
dictionary_to_store_heard_sounds = {}
#keys of dictionary will be  the ordered param lists

track_unique_objects = []
sounds_to_plot = []
times_of_sounds_to_plot = []
delta_t = []
OUTPUT_DIR = DIRECTORY + f"/{0}/"
received_sounds_sorted_by_time = read_data_per_simulation_per_bat(
    OUTPUT_DIR, "received"
)
# print(received_sounds_sorted_by_time)
if len(received_sounds_sorted_by_time)==0:
    raise ValueError("empty dir")

print(received_sounds_sorted_by_time)

117
([array([{'all_spl_values': [np.float64(80.92667106108051), np.float64(80.92903327412971)], 'occurance_times': [np.float64(0.034), np.float64(0.035)], 'ids': [UUID('a0ce4ec7-6167-4a90-88c6-7ac444ce309a'), UUID('a0ce4ec7-6167-4a90-88c6-7ac444ce309a')], 'origin': (np.float64(8.0), np.float64(0.01)), 'emitter_id': 30, 'bat_direction': Vector(0.942, 0.335), 'incident_direction': Vector(2.898, -3.526), 'type': 'direct', 'reflected_from': None, 'sound_object_id': UUID('a0ce4ec7-6167-4a90-88c6-7ac444ce309a'), 'bat_last_call_time': np.float64(0.024), 'sound_direction': Vector(0.405, 0.915), 'theta': np.float64(-170.58509691039075), 'bat_position': Vector(5.102, 3.536), 'distance_from_bat': 4.564462113327265, 'creation_time': np.float64(0.02), 'received_spl': np.float64(80.928), 'time': np.float64(0.034), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(104.26008719361505), np.float64(104.26209370433693)], 'occurance_times': [np.float64(0.034), np.float64(0.035)], 'ids': [UUID('20327ba5-4ab7-4534-8072-5653a7bd26bc'), UUID('20327ba5-4ab7-4534-8072-5653a7bd26bc')], 'origin': (np.float64(8.0), np.float64(0.0001)), 'emitter_id': 30, 'bat_direction': Vector(0.942, 0.335), 'incident_direction': Vector(2.898, -3.536), 'type': 'echo', 'reflected_from': 'wall_obstacle_60', 'sound_object_id': UUID('20327ba5-4ab7-4534-8072-5653a7bd26bc'), 'bat_last_call_time': np.float64(0.024), 'sound_direction': Vector(0.000, 1.000), 'theta': np.float64(-170.66386813345432), 'bat_position': Vector(5.102, 3.536), 'distance_from_bat': 4.57211486316781, 'creation_time': np.float64(0.020028862973760934), 'received_spl': np.float64(104.261), 'time': np.float64(0.034), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(72.96032792912604), np.float64(72.96324046713809)], 'occurance_times': [np.float64(0.034), np.float64(0.035)], 'ids': [UUID('1549ff5d-6286-4a0f-9763-65fbf960796d'), UUID('1549ff5d-6286-4a0f-9763-65fbf960796d')], 'origin': (np.float64(7.5001), np.float64(0.0)), 'emitter_id': 30, 'bat_direction': Vector(0.942, 0.335), 'incident_direction': Vector(2.398, -3.536), 'type': 'echo', 'reflected_from': 'wall_obstacle_59', 'sound_object_id': UUID('1549ff5d-6286-4a0f-9763-65fbf960796d'), 'bat_last_call_time': np.float64(0.024), 'sound_direction': Vector(1.000, 0.020), 'theta': np.float64(-175.85641453674415), 'bat_position': Vector(5.102, 3.536), 'distance_from_bat': 4.272856330137956, 'creation_time': np.float64(0.021457725976676386), 'received_spl': np.float64(72.962), 'time': np.float64(0.034), 'duration': np.float64(0.002)}],
      dtype=object), array([{'all_spl_values': [np.float64(72.57675779858336), np.float64(72.58535121586492)], 'occurance_times': [np.float64(0.076), np.float64(0.077)], 'ids': [UUID('50c31e36-cd19-42ea-a595-5b01c615fe6a'), UUID('50c31e36-cd19-42ea-a595-5b01c615fe6a')], 'origin': (np.float64(8.0), np.float64(6.99)), 'emitter_id': 21, 'bat_direction': Vector(0.971, 0.240), 'incident_direction': Vector(2.777, 3.419), 'type': 'direct', 'reflected_from': None, 'sound_object_id': UUID('50c31e36-cd19-42ea-a595-5b01c615fe6a'), 'bat_last_call_time': np.float64(0.068), 'sound_direction': Vector(0.456, -0.890), 'theta': np.float64(-69.08731658719074), 'bat_position': Vector(5.223, 3.571), 'distance_from_bat': 4.404602202072282, 'creation_time': np.float64(0.063), 'received_spl': np.float64(72.581), 'time': np.float64(0.076), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(89.98448927397274), np.float64(89.9928183607487)], 'occurance_times': [np.float64(0.076), np.float64(0.077)], 'ids': [UUID('af756497-76b8-47a4-8660-88cc13e0bd32'), UUID('af756497-76b8-47a4-8660-88cc13e0bd32')], 'origin': (np.float64(8.0), np.float64(6.9999)), 'emitter_id': 21, 'bat_direction': Vector(0.971, 0.240), 'incident_direction': Vector(2.777, 3.429), 'type': 'echo', 'reflected_from': 'wall_obstacle_41', 'sound_object_id': UUID('af756497-76b8-47a4-8660-88cc13e0bd32'), 'bat_last_call_time': np.float64(0.068), 'sound_direction': Vector(0.000, -1.000), 'theta': np.float64(-69.00626121709787), 'bat_position': Vector(5.223, 3.571), 'distance_from_bat': 4.41229085742316, 'creation_time': np.float64(0.06302886297376094), 'received_spl': np.float64(89.989), 'time': np.float64(0.076), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(68.5248138596862), np.float64(68.53255177420483)], 'occurance_times': [np.float64(0.077), np.float64(0.078)], 'ids': [UUID('b8248823-812c-4a1e-a887-e04f6787ad2c'), UUID('b8248823-812c-4a1e-a887-e04f6787ad2c')], 'origin': (np.float64(7.5001), np.float64(7.0)), 'emitter_id': 21, 'bat_direction': Vector(0.971, 0.240), 'incident_direction': Vector(2.274, 3.428), 'type': 'echo', 'reflected_from': 'wall_obstacle_40', 'sound_object_id': UUID('b8248823-812c-4a1e-a887-e04f6787ad2c'), 'bat_last_call_time': np.float64(0.068), 'sound_direction': Vector(1.000, -0.020), 'theta': np.float64(-63.561773650975425), 'bat_position': Vector(5.226, 3.572), 'distance_from_bat': 4.113897167042462, 'creation_time': np.float64(0.06445772597667639), 'received_spl': np.float64(68.529), 'time': np.float64(0.077), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(62.640576130939984), np.float64(62.647853311109095)], 'occurance_times': [np.float64(0.078), np.float64(0.079)], 'ids': [UUID('81d4c06d-0cc8-4791-8a03-0d52fdc548ed'), UUID('81d4c06d-0cc8-4791-8a03-0d52fdc548ed')], 'origin': (np.float64(7.0001), np.float64(7.0)), 'emitter_id': 21, 'bat_direction': Vector(0.971, 0.240), 'incident_direction': Vector(1.771, 3.427), 'type': 'echo', 'reflected_from': 'wall_obstacle_39', 'sound_object_id': UUID('81d4c06d-0cc8-4791-8a03-0d52fdc548ed'), 'bat_last_call_time': np.float64(0.068), 'sound_direction': Vector(1.000, -0.010), 'theta': np.float64(-57.331829100262844), 'bat_position': Vector(5.229, 3.573), 'distance_from_bat': 3.8580546888943914, 'creation_time': np.float64(0.06591530613338246), 'received_spl': np.float64(62.644), 'time': np.float64(0.078), 'duration': np.float64(0.002)}],
      dtype=object), array([{'all_spl_values': [np.float64(73.09068603624415), np.float64(73.09585208763154)], 'occurance_times': [np.float64(0.168), np.float64(0.169)], 'ids': [UUID('cccca6a0-4441-4872-9c0f-567e82c860b2'), UUID('cccca6a0-4441-4872-9c0f-567e82c860b2')], 'origin': (np.float64(8.0), np.float64(6.99)), 'emitter_id': 21, 'bat_direction': Vector(1.000, -0.015), 'incident_direction': Vector(2.593, 3.398), 'type': 'direct', 'reflected_from': None, 'sound_object_id': UUID('cccca6a0-4441-4872-9c0f-567e82c860b2'), 'bat_last_call_time': np.float64(0.165), 'sound_direction': Vector(0.456, -0.890), 'theta': np.float64(-67.34346281747713), 'bat_position': Vector(5.407, 3.592), 'distance_from_bat': 4.2744560104181675, 'creation_time': np.float64(0.155), 'received_spl': np.float64(73.093), 'time': np.float64(0.168), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(90.47764173040903), np.float64(90.4825442822205)], 'occurance_times': [np.float64(0.168), np.float64(0.169)], 'ids': [UUID('3682680b-51d9-4d48-b3c3-ff9b559b4cf5'), UUID('3682680b-51d9-4d48-b3c3-ff9b559b4cf5')], 'origin': (np.float64(8.0), np.float64(6.9999)), 'emitter_id': 21, 'bat_direction': Vector(1.000, -0.015), 'incident_direction': Vector(2.593, 3.408), 'type': 'echo', 'reflected_from': 'wall_obstacle_41', 'sound_object_id': UUID('3682680b-51d9-4d48-b3c3-ff9b559b4cf5'), 'bat_last_call_time': np.float64(0.165), 'sound_direction': Vector(0.000, -1.000), 'theta': np.float64(-67.26311496151963), 'bat_position': Vector(5.407, 3.592), 'distance_from_bat': 4.282330854219464, 'creation_time': np.float64(0.15502886297376092), 'received_spl': np.float64(90.48), 'time': np.float64(0.168), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(68.96024116138068), np.float64(68.96437237748185)], 'occurance_times': [np.float64(0.169), np.float64(0.17)], 'ids': [UUID('73f8b2b5-5496-4861-8ba6-c325cb8147c0'), UUID('73f8b2b5-5496-4861-8ba6-c325cb8147c0')], 'origin': (np.float64(7.5001), np.float64(7.0)), 'emitter_id': 21, 'bat_direction': Vector(1.000, -0.015), 'incident_direction': Vector(2.091, 3.408), 'type': 'echo', 'reflected_from': 'wall_obstacle_40', 'sound_object_id': UUID('73f8b2b5-5496-4861-8ba6-c325cb8147c0'), 'bat_last_call_time': np.float64(0.165), 'sound_direction': Vector(1.000, -0.020), 'theta': np.float64(-61.52874043673907), 'bat_position': Vector(5.409, 3.592), 'distance_from_bat': 3.9985552967165527, 'creation_time': np.float64(0.15645772597667637), 'received_spl': np.float64(68.962), 'time': np.float64(0.169), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(63.029201504678106), np.float64(63.032793087479206)], 'occurance_times': [np.float64(0.169), np.float64(0.17)], 'ids': [UUID('2abb15c5-bea4-4758-acbb-f93240a70d3d'), UUID('2abb15c5-bea4-4758-acbb-f93240a70d3d')], 'origin': (np.float64(7.0001), np.float64(7.0)), 'emitter_id': 21, 'bat_direction': Vector(1.000, -0.015), 'incident_direction': Vector(1.591, 3.408), 'type': 'echo', 'reflected_from': 'wall_obstacle_39', 'sound_object_id': UUID('2abb15c5-bea4-4758-acbb-f93240a70d3d'), 'bat_last_call_time': np.float64(0.165), 'sound_direction': Vector(1.000, -0.010), 'theta': np.float64(-55.02267030647543), 'bat_position': Vector(5.409, 3.592), 'distance_from_bat': 3.761315522646299, 'creation_time': np.float64(0.15791530613338248), 'received_spl': np.float64(63.031), 'time': np.float64(0.169), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(75.247347298365), np.float64(75.25419974069405)], 'occurance_times': [np.float64(0.173), np.float64(0.174)], 'ids': [UUID('6c8b63f5-f996-4da2-854c-e58603102c02'), UUID('6c8b63f5-f996-4da2-854c-e58603102c02')], 'origin': (np.float64(9.99), np.float64(5.0)), 'emitter_id': 12, 'bat_direction': Vector(1.000, -0.015), 'incident_direction': Vector(4.573, 1.408), 'type': 'direct', 'reflected_from': None, 'sound_object_id': UUID('6c8b63f5-f996-4da2-854c-e58603102c02'), 'bat_last_call_time': np.float64(0.165), 'sound_direction': Vector(0.772, -0.635), 'theta': np.float64(-102.88158867874156), 'bat_position': Vector(5.417, 3.592), 'distance_from_bat': 4.784824728503647, 'creation_time': np.float64(0.159), 'received_spl': np.float64(75.251), 'time': np.float64(0.173), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(91.01608759505378), np.float64(91.0205742647044)], 'occurance_times': [np.float64(0.174), np.float64(0.175)], 'ids': [UUID('8c93ec64-e59b-432f-a73a-5efc84d518c3'), UUID('8c93ec64-e59b-432f-a73a-5efc84d518c3')], 'origin': (np.float64(9.9999), np.float64(5.0)), 'emitter_id': 12, 'bat_direction': Vector(1.000, -0.015), 'incident_direction': Vector(4.581, 1.408), 'type': 'echo', 'reflected_from': 'wall_obstacle_22', 'sound_object_id': UUID('8c93ec64-e59b-432f-a73a-5efc84d518c3'), 'bat_last_call_time': np.float64(0.165), 'sound_direction': Vector(-1.000, 0.000), 'theta': np.float64(-102.90904675227478), 'bat_position': Vector(5.419, 3.592), 'distance_from_bat': 4.792384127696777, 'creation_time': np.float64(0.15902886297376093), 'received_spl': np.float64(91.018), 'time': np.float64(0.174), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(69.39191478834555), np.float64(69.39618876634046)], 'occurance_times': [np.float64(0.175), np.float64(0.176)], 'ids': [UUID('511d9f2a-8568-4a6c-a73f-6f225b053812'), UUID('511d9f2a-8568-4a6c-a73f-6f225b053812')], 'origin': (np.float64(10.0), np.float64(4.5001)), 'emitter_id': 12, 'bat_direction': Vector(1.000, -0.015), 'incident_direction': Vector(4.579, 0.909), 'type': 'echo', 'reflected_from': 'wall_obstacle_21', 'sound_object_id': UUID('511d9f2a-8568-4a6c-a73f-6f225b053812'), 'bat_last_call_time': np.float64(0.165), 'sound_direction': Vector(-0.020, 1.000), 'theta': np.float64(-108.77683190091749), 'bat_position': Vector(5.421, 3.592), 'distance_from_bat': 4.668120456468535, 'creation_time': np.float64(0.16045772597667637), 'received_spl': np.float64(69.394), 'time': np.float64(0.175), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(63.41896686667849)], 'occurance_times': [np.float64(0.176)], 'ids': [UUID('68fab5d5-1d52-4f70-8117-6e3a3e964726')], 'origin': (np.float64(10.0), np.float64(4.0001)), 'emitter_id': 12, 'bat_direction': Vector(1.000, -0.015), 'incident_direction': Vector(4.579, 0.409), 'type': 'echo', 'reflected_from': 'wall_obstacle_20', 'sound_object_id': UUID('68fab5d5-1d52-4f70-8117-6e3a3e964726'), 'bat_last_call_time': np.float64(0.165), 'sound_direction': Vector(-0.010, 1.000), 'theta': np.float64(-114.90112403682525), 'bat_position': Vector(5.421, 3.592), 'distance_from_bat': 4.5970412871867925, 'creation_time': np.float64(0.16191530613338248), 'received_spl': np.float64(63.419), 'time': np.float64(0.176), 'duration': np.float64(0.001)}],
      dtype=object), array([{'all_spl_values': [np.float64(69.61324482633133)], 'occurance_times': [np.float64(0.268)], 'ids': [UUID('d00926f9-88ce-4236-9910-841a9b1a4d49')], 'origin': (np.float64(6.5001), np.float64(7.0)), 'emitter_id': 20, 'bat_direction': Vector(1.000, -0.015), 'incident_direction': Vector(0.895, 3.411), 'type': 'echo', 'reflected_from': 'wall_obstacle_38', 'sound_object_id': UUID('d00926f9-88ce-4236-9910-841a9b1a4d49'), 'bat_last_call_time': np.float64(0.266), 'sound_direction': Vector(1.000, -0.020), 'theta': np.float64(-44.700509937417564), 'bat_position': Vector(5.605, 3.589), 'distance_from_bat': 3.5266637762763833, 'creation_time': np.float64(0.2564577259766764), 'received_spl': np.float64(69.613), 'time': np.float64(0.268), 'duration': np.float64(0.001)},
       {'all_spl_values': [np.float64(63.21608174952828), np.float64(63.21760335747339)], 'occurance_times': [np.float64(0.268), np.float64(0.269)], 'ids': [UUID('bb663db4-3a04-4f00-a402-d9d843560774'), UUID('bb663db4-3a04-4f00-a402-d9d843560774')], 'origin': (np.float64(6.0001), np.float64(7.0)), 'emitter_id': 20, 'bat_direction': Vector(1.000, -0.015), 'incident_direction': Vector(0.393, 3.411), 'type': 'echo', 'reflected_from': 'wall_obstacle_37', 'sound_object_id': UUID('bb663db4-3a04-4f00-a402-d9d843560774'), 'bat_last_call_time': np.float64(0.266), 'sound_direction': Vector(1.000, -0.010), 'theta': np.float64(-36.57106318269075), 'bat_position': Vector(5.607, 3.589), 'distance_from_bat': 3.433807837517994, 'creation_time': np.float64(0.2579153061333825), 'received_spl': np.float64(63.217), 'time': np.float64(0.268), 'duration': np.float64(0.002)}],
      dtype=object), array([{'all_spl_values': [np.float64(72.12205472667223)], 'occurance_times': [np.float64(0.319)], 'ids': [UUID('d4d031aa-219c-49eb-9084-557792f3cbae')], 'origin': (np.float64(9.99), np.float64(6.0)), 'emitter_id': 13, 'bat_direction': Vector(1.000, -0.015), 'incident_direction': Vector(4.241, 2.414), 'type': 'direct', 'reflected_from': None, 'sound_object_id': UUID('d4d031aa-219c-49eb-9084-557792f3cbae'), 'bat_last_call_time': np.float64(0.317), 'sound_direction': Vector(0.507, -0.862), 'theta': np.float64(-90.35453642164848), 'bat_position': Vector(5.749, 3.586), 'distance_from_bat': 4.8795722569299045, 'creation_time': np.float64(0.303), 'received_spl': np.float64(72.122), 'time': np.float64(0.319), 'duration': np.float64(0.001)},
       {'all_spl_values': [np.float64(72.14913479175438)], 'occurance_times': [np.float64(0.319)], 'ids': [UUID('21710b8a-8255-454d-ba71-52bf31725728')], 'origin': (np.float64(10.0), np.float64(1.5001)), 'emitter_id': 9, 'bat_direction': Vector(1.000, -0.015), 'incident_direction': Vector(4.251, -2.086), 'type': 'echo', 'reflected_from': 'wall_obstacle_15', 'sound_object_id': UUID('21710b8a-8255-454d-ba71-52bf31725728'), 'bat_last_call_time': np.float64(0.317), 'sound_direction': Vector(-0.020, 1.000), 'theta': np.float64(-146.14171480426967), 'bat_position': Vector(5.749, 3.586), 'distance_from_bat': 4.735231265587775, 'creation_time': np.float64(0.30345772597667636), 'received_spl': np.float64(72.149), 'time': np.float64(0.319), 'duration': np.float64(0.001)},
       {'all_spl_values': [np.float64(87.71201050708352)], 'occurance_times': [np.float64(0.319)], 'ids': [UUID('daa59a16-edef-4785-be60-40c9834085c8')], 'origin': (np.float64(9.9999), np.float64(6.0)), 'emitter_id': 13, 'bat_direction': Vector(1.000, -0.015), 'incident_direction': Vector(4.251, 2.414), 'type': 'echo', 'reflected_from': 'wall_obstacle_24', 'sound_object_id': UUID('daa59a16-edef-4785-be60-40c9834085c8'), 'bat_last_call_time': np.float64(0.317), 'sound_direction': Vector(-1.000, 0.000), 'theta': np.float64(-90.41193386636071), 'bat_position': Vector(5.749, 3.586), 'distance_from_bat': 4.888178827600316, 'creation_time': np.float64(0.3030288629737609), 'received_spl': np.float64(87.712), 'time': np.float64(0.319), 'duration': np.float64(0.001)},
       {'all_spl_values': [np.float64(66.30243788385991), np.float64(66.30835348826425)], 'occurance_times': [np.float64(0.319), np.float64(0.32)], 'ids': [UUID('c5963ec2-007d-4bdc-80c2-35818f08a72c'), UUID('c5963ec2-007d-4bdc-80c2-35818f08a72c')], 'origin': (np.float64(10.0), np.float64(5.5001)), 'emitter_id': 13, 'bat_direction': Vector(1.000, -0.015), 'incident_direction': Vector(4.248, 1.914), 'type': 'echo', 'reflected_from': 'wall_obstacle_23', 'sound_object_id': UUID('c5963ec2-007d-4bdc-80c2-35818f08a72c'), 'bat_last_call_time': np.float64(0.317), 'sound_direction': Vector(-0.020, 1.000), 'theta': np.float64(-95.74748687872207), 'bat_position': Vector(5.752, 3.586), 'distance_from_bat': 4.659037498250041, 'creation_time': np.float64(0.30445772597667636), 'received_spl': np.float64(66.305), 'time': np.float64(0.319), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(60.661302464058586), np.float64(60.667775763948384)], 'occurance_times': [np.float64(0.319), np.float64(0.32)], 'ids': [UUID('d2d78c7a-cd99-43d0-b86e-f61c1c85cae7'), UUID('d2d78c7a-cd99-43d0-b86e-f61c1c85cae7')], 'origin': (np.float64(10.0), np.float64(5.0001)), 'emitter_id': 13, 'bat_direction': Vector(1.000, -0.015), 'incident_direction': Vector(4.248, 1.414), 'type': 'echo', 'reflected_from': 'wall_obstacle_22', 'sound_object_id': UUID('d2d78c7a-cd99-43d0-b86e-f61c1c85cae7'), 'bat_last_call_time': np.float64(0.317), 'sound_direction': Vector(-0.010, 1.000), 'theta': np.float64(-101.59187179210458), 'bat_position': Vector(5.752, 3.586), 'distance_from_bat': 4.476928680479509, 'creation_time': np.float64(0.30591530613338247), 'received_spl': np.float64(60.665), 'time': np.float64(0.319), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(65.18677621663872), np.float64(65.19203910032267)], 'occurance_times': [np.float64(0.32), np.float64(0.321)], 'ids': [UUID('6b046ae9-8fa8-44b9-877d-9f445a3cfcf3'), UUID('6b046ae9-8fa8-44b9-877d-9f445a3cfcf3')], 'origin': (np.float64(10.0), np.float64(1.0001)), 'emitter_id': 9, 'bat_direction': Vector(1.000, -0.015), 'incident_direction': Vector(4.245, -2.586), 'type': 'echo', 'reflected_from': 'wall_obstacle_14', 'sound_object_id': UUID('6b046ae9-8fa8-44b9-877d-9f445a3cfcf3'), 'bat_last_call_time': np.float64(0.317), 'sound_direction': Vector(-0.010, 1.000), 'theta': np.float64(-151.35219663570666), 'bat_position': Vector(5.755, 3.586), 'distance_from_bat': 4.970637150969682, 'creation_time': np.float64(0.30491530613338247), 'received_spl': np.float64(65.189), 'time': np.float64(0.32), 'duration': np.float64(0.002)},

In [20]:
received_sounds_sorted_by_time[0][1][0]

{'all_spl_values': [np.float64(72.57675779858336),
  np.float64(72.58535121586492)],
 'occurance_times': [np.float64(0.076), np.float64(0.077)],
 'ids': [UUID('50c31e36-cd19-42ea-a595-5b01c615fe6a'),
  UUID('50c31e36-cd19-42ea-a595-5b01c615fe6a')],
 'origin': (np.float64(8.0), np.float64(6.99)),
 'emitter_id': 21,
 'bat_direction': Vector(0.971, 0.240),
 'incident_direction': Vector(2.777, 3.419),
 'type': 'direct',
 'reflected_from': None,
 'sound_object_id': UUID('50c31e36-cd19-42ea-a595-5b01c615fe6a'),
 'bat_last_call_time': np.float64(0.068),
 'sound_direction': Vector(0.456, -0.890),
 'theta': np.float64(-69.08731658719074),
 'bat_position': Vector(5.223, 3.571),
 'distance_from_bat': 4.404602202072282,
 'creation_time': np.float64(0.063),
 'received_spl': np.float64(72.581),
 'time': np.float64(0.076),
 'duration': np.float64(0.002)}

In [21]:
new_df = pd.DataFrame()
new_df
# for key in new_df.keys():
#     new_df[key] = []
    
print(new_df)

for i, call_frame in enumerate(received_sounds_sorted_by_time[0]):
    for j, sound in enumerate(call_frame):
        for key in sound.keys():
            if isinstance(sound[key], list):
                sound[key] = sound[key][0]
        
        _sound_df = pd.DataFrame(sound)
        new_df = pd.concat((new_df,_sound_df))
        
new_df

Empty DataFrame
Columns: []
Index: []

,all_spl_values,occurance_times,ids,origin,emitter_id,bat_direction,incident_direction,type,reflected_from,sound_object_id,bat_last_call_time,sound_direction,theta,bat_position,distance_from_bat,creation_time,received_spl,time,duration
0,80.926671,0.034,a0ce4ec7-6167-4a90-88c6-7ac444ce309a,8.0000,30,"Vector(0.942, 0.335)","Vector(2.898, -3.526)",direct,None,a0ce4ec7-6167-4a90-88c6-7ac444ce309a,0.024,"Vector(0.405, 0.915)",-170.585097,"Vector(5.102, 3.536)",4.564462,0.020000,80.928,0.034,0.002
1,80.926671,0.034,a0ce4ec7-6167-4a90-88c6-7ac444ce309a,0.0100,30,"Vector(0.942, 0.335)","Vector(2.898, -3.526)",direct,None,a0ce4ec7-6167-4a90-88c6-7ac444ce309a,0.024,"Vector(0.405, 0.915)",-170.585097,"Vector(5.102, 3.536)",4.564462,0.020000,80.928,0.034,0.002
0,104.260087,0.034,20327ba5-4ab7-4534-8072-5653a7bd26bc,8.0000,30,"Vector(0.942, 0.335)","Vector(2.898, -3.536)",echo,wall_obstacle_60,20327ba5-4ab7-4534-8072-5653a7bd26bc,0.024,"Vector(0.000, 1.000)",-170.663868,"Vector(5.102, 3.536)",4.572115,0.020029,104.261,0.034,0.002
1,104.260087,0.034,20327ba5-4ab7-4534-8072-5653a7bd26bc,0.0001,30,"Vector(0.942, 0.335)","Vector(2.898, -3.536)",echo,wall_obstacle_60,20327ba5-4ab7-4534-8072-5653a7bd26bc,0.024,"Vector(0.000, 1.000)",-170.663868,"Vector(5.102, 3.536)",4.572115,0.020029,104.261,0.034,0.002
0,72.960328,0.034,1549ff5d-6286-4a0f-9763-65fbf960796d,7.5001,30,"Vector(0.942, 0.335)","Vector(2.398, -3.536)",echo,wall_obstacle_59,1549ff5d-6286-4a0f-9763-65fbf960796d,0.024,"Vector(1.000, 0.020)",-175.856415,"Vector(5.102, 3.536)",4.272856,0.021458,72.962,0.034,0.002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,101.387925,9.965,a75c5bc7-215c-4663-9fbc-29c4d825841d,6.0000,7,"Vector(-0.930, 0.368)","Vector(-6.149, 2.187)",echo,wall_obstacle_11,a75c5bc7-215c-4663-9fbc-29c4d825841d,9.958,"Vector(1.000, 0.000)",40.420399,"Vector(6.149, 3.813)",6.526122,9.945029,101.390,9.965,0.002
0,64.439372,9.967,69833fec-c97f-43c9-bd2e-9b8fc9be6c85,0.0000,7,"Vector(-0.930, 0.368)","Vector(-6.147, 1.686)",echo,wall_obstacle_10,69833fec-c97f-43c9-bd2e-9b8fc9be6c85,9.958,"Vector(0.020, 1.000)",44.658905,"Vector(6.147, 3.814)",6.374124,9.946458,64.439,9.967,0.001
1,64.439372,9.967,69833fec-c97f-43c9-bd2e-9b8fc9be6c85,5.5001,7,"Vector(-0.930, 0.368)","Vector(-6.147, 1.686)",echo,wall_obstacle_10,69833fec-c97f-43c9-bd2e-9b8fc9be6c85,9.958,"Vector(0.020, 1.000)",44.658905,"Vector(6.147, 3.814)",6.374124,9.946458,64.439,9.967,0.001
0,89.587726,9.968,7b470a09-4e57-45c2-8650-9e919905f240,1.0000,23,"Vector(-0.930, 0.368)","Vector(-5.143, -3.815)",echo,wall_obstacle_46,7b470a09-4e57-45c2-8650-9e919905f240,9.958,"Vector(0.000, 1.000)",96.566777,"Vector(6.143, 3.815)",6.403780,9.949029,89.590,9.968,0.002
1,89.587726,9.968,7b470a09-4e57-45c2-8650-9e919905f240,0.0001,23,"Vector(-0.930, 0.368)","Vector(-5.143, -3.815)",echo,wall_obstacle_46,7b470a09-4e57-45c2-8650-9e919905f240,9.958,"Vector(0.000, 1.000)",96.566777,"Vector(6.143, 3.815)",6.403780,9.949029,89.590,9.968,0.002

In [22]:
new_df.sort_values("time")

,all_spl_values,occurance_times,ids,origin,emitter_id,bat_direction,incident_direction,type,reflected_from,sound_object_id,bat_last_call_time,sound_direction,theta,bat_position,distance_from_bat,creation_time,received_spl,time,duration
0,80.926671,0.034,a0ce4ec7-6167-4a90-88c6-7ac444ce309a,8.0000,30,"Vector(0.942, 0.335)","Vector(2.898, -3.526)",direct,None,a0ce4ec7-6167-4a90-88c6-7ac444ce309a,0.024,"Vector(0.405, 0.915)",-170.585097,"Vector(5.102, 3.536)",4.564462,0.020000,80.928,0.034,0.002
1,80.926671,0.034,a0ce4ec7-6167-4a90-88c6-7ac444ce309a,0.0100,30,"Vector(0.942, 0.335)","Vector(2.898, -3.526)",direct,None,a0ce4ec7-6167-4a90-88c6-7ac444ce309a,0.024,"Vector(0.405, 0.915)",-170.585097,"Vector(5.102, 3.536)",4.564462,0.020000,80.928,0.034,0.002
0,104.260087,0.034,20327ba5-4ab7-4534-8072-5653a7bd26bc,8.0000,30,"Vector(0.942, 0.335)","Vector(2.898, -3.536)",echo,wall_obstacle_60,20327ba5-4ab7-4534-8072-5653a7bd26bc,0.024,"Vector(0.000, 1.000)",-170.663868,"Vector(5.102, 3.536)",4.572115,0.020029,104.261,0.034,0.002
1,104.260087,0.034,20327ba5-4ab7-4534-8072-5653a7bd26bc,0.0001,30,"Vector(0.942, 0.335)","Vector(2.898, -3.536)",echo,wall_obstacle_60,20327ba5-4ab7-4534-8072-5653a7bd26bc,0.024,"Vector(0.000, 1.000)",-170.663868,"Vector(5.102, 3.536)",4.572115,0.020029,104.261,0.034,0.002
0,72.960328,0.034,1549ff5d-6286-4a0f-9763-65fbf960796d,7.5001,30,"Vector(0.942, 0.335)","Vector(2.398, -3.536)",echo,wall_obstacle_59,1549ff5d-6286-4a0f-9763-65fbf960796d,0.024,"Vector(1.000, 0.020)",-175.856415,"Vector(5.102, 3.536)",4.272856,0.021458,72.962,0.034,0.002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,101.387925,9.965,a75c5bc7-215c-4663-9fbc-29c4d825841d,6.0000,7,"Vector(-0.930, 0.368)","Vector(-6.149, 2.187)",echo,wall_obstacle_11,a75c5bc7-215c-4663-9fbc-29c4d825841d,9.958,"Vector(1.000, 0.000)",40.420399,"Vector(6.149, 3.813)",6.526122,9.945029,101.390,9.965,0.002
0,64.439372,9.967,69833fec-c97f-43c9-bd2e-9b8fc9be6c85,0.0000,7,"Vector(-0.930, 0.368)","Vector(-6.147, 1.686)",echo,wall_obstacle_10,69833fec-c97f-43c9-bd2e-9b8fc9be6c85,9.958,"Vector(0.020, 1.000)",44.658905,"Vector(6.147, 3.814)",6.374124,9.946458,64.439,9.967,0.001
1,64.439372,9.967,69833fec-c97f-43c9-bd2e-9b8fc9be6c85,5.5001,7,"Vector(-0.930, 0.368)","Vector(-6.147, 1.686)",echo,wall_obstacle_10,69833fec-c97f-43c9-bd2e-9b8fc9be6c85,9.958,"Vector(0.020, 1.000)",44.658905,"Vector(6.147, 3.814)",6.374124,9.946458,64.439,9.967,0.001
0,89.587726,9.968,7b470a09-4e57-45c2-8650-9e919905f240,1.0000,23,"Vector(-0.930, 0.368)","Vector(-5.143, -3.815)",echo,wall_obstacle_46,7b470a09-4e57-45c2-8650-9e919905f240,9.958,"Vector(0.000, 1.000)",96.566777,"Vector(6.143, 3.815)",6.403780,9.949029,89.590,9.968,0.002
1,89.587726,9.968,7b470a09-4e57-45c2-8650-9e919905f240,0.0001,23,"Vector(-0.930, 0.368)","Vector(-5.143, -3.815)",echo,wall_obstacle_46,7b470a09-4e57-45c2-8650-9e919905f240,9.958,"Vector(0.000, 1.000)",96.566777,"Vector(6.143, 3.815)",6.403780,9.949029,89.590,9.968,0.002

In [23]:
new_df["delta_t"] = new_df["time"]-new_df["bat_last_call_time"]
new_df = new_df.reset_index()

In [24]:
np.unique(new_df["bat_last_call_time"].values)

array([0.024, 0.068, 0.165, 0.266, 0.317, 0.366, 0.472, 0.52 , 0.564,
       0.608, 0.657, 0.709, 0.759, 0.809, 0.908, 1.012, 1.071, 1.166,
       1.214, 1.257, 1.308, 1.413, 1.515, 1.612, 1.712, 1.821, 1.93 ,
       2.021, 2.118, 2.215, 2.32 , 2.416, 2.522, 2.631, 2.74 , 2.848,
       2.945, 3.046, 3.15 , 3.26 , 3.376, 3.42 , 3.476, 3.519, 3.618,
       3.713, 3.823, 3.933, 4.027, 4.127, 4.23 , 4.335, 4.426, 4.532,
       4.625, 4.719, 4.827, 4.931, 5.038, 5.137, 5.237, 5.33 , 5.436,
       5.54 , 5.588, 5.697, 5.806, 5.905, 6.011, 6.116, 6.159, 6.262,
       6.37 , 6.477, 6.57 , 6.612, 6.661, 6.719, 6.813, 6.908, 6.999,
       7.103, 7.197, 7.292, 7.386, 7.483, 7.593, 7.697, 7.8  , 7.893,
       7.993, 8.103, 8.194, 8.293, 8.39 , 8.484, 8.591, 8.693, 8.798,
       8.898, 8.999, 9.103, 9.154, 9.198, 9.243, 9.29 , 9.393, 9.494,
       9.6  , 9.701, 9.81 , 9.863, 9.958])

In [25]:
filtered_df = new_df.loc[(new_df['theta']<=30) & (new_df['theta']>=-30)]
filtered_df
grouby_call_time = new_df.groupby("bat_last_call_time")
np.unique(filtered_df["bat_last_call_time"].values)

array([1.612, 1.712, 1.821, 1.93 , 2.021, 2.118, 2.416, 2.522, 2.631,
       2.74 , 2.848, 2.945, 3.476, 3.823, 5.436, 6.159, 6.262, 6.37 ,
       6.477, 6.57 , 6.612, 6.661, 6.719, 6.813, 6.908, 6.999, 7.103,
       8.194, 8.293, 8.591, 8.898, 8.999, 9.103, 9.198, 9.29 , 9.393,
       9.494, 9.701, 9.81 , 9.863])

In [26]:
filtered_df = new_df.loc[(new_df["emitter_id"]==0)]
filtered_df
grouby_call_time = new_df.groupby("bat_last_call_time")
np.unique(filtered_df["bat_last_call_time"].values)

array([1.214, 1.257, 1.308, 1.413, 1.515, 1.612, 1.712, 1.821, 1.93 ,
       2.118, 2.215, 2.32 , 2.416, 2.522, 2.631, 2.74 , 2.848, 2.945,
       3.046, 3.15 , 3.26 , 3.376, 3.42 , 3.476, 3.519, 3.618, 3.713,
       3.823, 4.127, 4.23 , 4.335, 4.426, 4.532, 4.625, 4.719, 4.827,
       4.931, 5.038, 5.137, 5.237, 5.33 , 5.436, 6.57 , 6.612, 6.661,
       6.719, 6.813, 6.908, 6.999, 7.103, 7.197, 7.292, 7.386, 7.483,
       7.593, 7.697, 7.8  , 7.893, 7.993, 8.103])

In [27]:

#first call
df = grouby_call_time.get_group(1.612)
df[["delta_t", "theta", "all_spl_values", "distance_from_bat", "bat_last_call_time", "emitter_id", "type", "bat_direction", "incident_direction", "reflected_from"]]

,delta_t,theta,all_spl_values,distance_from_bat,bat_last_call_time,emitter_id,type,bat_direction,incident_direction,reflected_from
448,0.006,24.067898,76.790069,5.069933,1.612,18,direct,"Vector(0.487, 0.873)","Vector(-4.105, 2.975)",None
449,0.006,24.067898,76.790069,5.069933,1.612,18,direct,"Vector(0.487, 0.873)","Vector(-4.105, 2.975)",None
450,0.006,23.977410,97.558991,5.075749,1.612,18,echo,"Vector(0.487, 0.873)","Vector(-4.105, 2.985)",wall_obstacle_35
451,0.006,23.977410,97.558991,5.075749,1.612,18,echo,"Vector(0.487, 0.873)","Vector(-4.105, 2.985)",wall_obstacle_35
452,0.006,-120.949591,71.272201,0.894833,1.612,0,echo,"Vector(0.487, 0.873)","Vector(0.895, -0.015)",wall_obstacle_20
453,0.006,-120.949591,71.272201,0.894833,1.612,0,echo,"Vector(0.487, 0.873)","Vector(0.895, -0.015)",wall_obstacle_20
454,0.006,-91.533300,68.185200,1.017775,1.612,0,echo,"Vector(0.487, 0.873)","Vector(0.895, 0.485)",wall_obstacle_21
455,0.006,-91.533300,68.185200,1.017775,1.612,0,echo,"Vector(0.487, 0.873)","Vector(0.895, 0.485)",wall_obstacle_21
456,0.008,-72.267790,63.855377,1.328835,1.612,0,echo,"Vector(0.487, 0.873)","Vector(0.894, 0.983)",wall_obstacle_22
457,0.008,-72.267790,63.855377,1.328835,1.612,0,echo,"Vector(0.487, 0.873)","Vector(0.894, 0.983)",wall_obstacle_22
458,0.009,27.109908,73.844790,5.487585,1.612,18,echo,"Vector(0.487, 0.873)","Vector(-4.608, 2.980)",wall_obstacle_34
459,0.009,27.109908,73.844790,5.487585,1.612,18,echo,"Vector(0.487, 0.873)","Vector(-4.608, 2.980)",wall_obstacle_34
460,0.009,-54.009233,83.150363,2.167448,1.612,13,direct,"Vector(0.487, 0.873)","Vector(0.882, 1.980)",None
461,0.009,-54.009233,83.150363,2.167448,1.612,13,direct,"Vector(0.487, 0.873)","Vector(0.882, 1.980)",None
462,0.009,-54.247849,96.868439,2.171495,1.612,13,echo,"Vector(0.487, 0.873)","Vector(0.892, 1.980)",wall_obstacle_24
463,0.009,-54.247849,96.868439,2.171495,1.612,13,echo,"Vector(0.487, 0.873)","Vector(0.892, 1.980)",wall_obstacle_24
464,0.009,-61.074290,76.702227,1.727989,1.612,13,echo,"Vector(0.487, 0.873)","Vector(0.892, 1.480)",wall_obstacle_23
465,0.009,-61.074290,76.702227,1.727989,1.612,13,echo,"Vector(0.487, 0.873)","Vector(0.892, 1.480)",wall_obstacle_23
466,0.009,-72.304799,73.244997,1.325113,1.612,13,echo,"Vector(0.487, 0.873)","Vector(0.892, 0.980)",wall_obstacle_22
467,0.009,-72.304799,73.244997,1.325113,1.612,13,echo,"Vector(0.487, 0.873)","Vector(0.892, 0.980)",wall_obstacle_22
468,0.010,-91.772148,72.197005,1.011187,1.612,13,echo,"Vector(0.487, 0.873)","Vector(0.891, 0.478)",wall_obstacle_21
469,0.010,-91.772148,72.197005,1.011187,1.612,13,echo,"Vector(0.487, 0.873)","Vector(0.891, 0.478)",wall_obstacle_21
470,0.011,-121.397169,70.740148,0.891195,1.612,13,echo,"Vector(0.487, 0.873)","Vector(0.891, -0.022)",wall_obstacle_20
471,0.011,-121.397169,70.740148,0.891195,1.612,13,echo,"Vector(0.487, 0.873)","Vector(0.891, -0.022)",wall_obstacle_20

In [28]:
# grouby_call_time = new_df.groupby("bat_last_call_time")
#first call

df = grouby_call_time.get_group(1.712)
df[["delta_t", "theta", "all_spl_values", "distance_from_bat", "bat_last_call_time", "emitter_id", "type", "bat_direction"]]

,delta_t,theta,all_spl_values,distance_from_bat,bat_last_call_time,emitter_id,type,bat_direction
472,0.002,33.663880,69.719910,6.332009,1.712,17,echo,"Vector(0.240, 0.971)"
473,0.002,33.663880,69.719910,6.332009,1.712,17,echo,"Vector(0.240, 0.971)"
474,0.002,28.998095,73.882554,5.453876,1.712,18,echo,"Vector(0.240, 0.971)"
475,0.002,28.998095,73.882554,5.453876,1.712,18,echo,"Vector(0.240, 0.971)"
476,0.004,35.587489,62.498126,6.782643,1.712,17,echo,"Vector(0.240, 0.971)"
477,0.004,35.587489,62.498126,6.782643,1.712,17,echo,"Vector(0.240, 0.971)"
478,0.004,31.561373,66.437130,5.886577,1.712,18,echo,"Vector(0.240, 0.971)"
479,0.004,31.561373,66.437130,5.886577,1.712,18,echo,"Vector(0.240, 0.971)"
480,0.005,-133.567338,72.121243,0.846718,1.712,0,echo,"Vector(0.240, 0.971)"
481,0.005,-133.567338,72.121243,0.846718,1.712,0,echo,"Vector(0.240, 0.971)"
482,0.006,33.752206,61.476311,6.329864,1.712,18,echo,"Vector(0.240, 0.971)"
483,0.006,33.752206,61.476311,6.329864,1.712,18,echo,"Vector(0.240, 0.971)"
484,0.006,-100.002399,69.802515,0.875401,1.712,0,echo,"Vector(0.240, 0.971)"
485,0.006,-100.002399,69.802515,0.875401,1.712,0,echo,"Vector(0.240, 0.971)"
486,0.007,-75.875864,65.301754,1.145336,1.712,0,echo,"Vector(0.240, 0.971)"
487,0.007,-75.875864,65.301754,1.145336,1.712,0,echo,"Vector(0.240, 0.971)"
488,0.009,-62.410521,60.600632,1.532178,1.712,0,echo,"Vector(0.240, 0.971)"
489,0.009,-62.410521,60.600632,1.532178,1.712,0,echo,"Vector(0.240, 0.971)"
490,0.011,-100.444616,63.139835,0.871033,1.712,8,echo,"Vector(0.240, 0.971)"
491,0.011,-100.444616,63.139835,0.871033,1.712,8,echo,"Vector(0.240, 0.971)"

In [29]:

grouby_call_time = new_df.groupby("bat_last_call_time")
#first call
df = grouby_call_time.get_group(1.821)
df[["delta_t", "theta", "all_spl_values", "distance_from_bat", "bat_last_call_time", "emitter_id", "type"]]

,delta_t,theta,all_spl_values,distance_from_bat,bat_last_call_time,emitter_id,type
492,0.002,35.542745,69.819334,6.258646,1.821,17,echo
493,0.002,35.542745,69.819334,6.258646,1.821,17,echo
494,0.004,-113.811840,63.716003,0.807747,1.821,8,echo
495,0.004,-113.811840,63.716003,0.807747,1.821,8,echo
496,0.005,37.339625,62.580646,6.715246,1.821,17,echo
497,0.005,37.339625,62.580646,6.715246,1.821,17,echo
498,0.005,-113.946566,70.102064,0.807543,1.821,0,echo
499,0.005,-113.946566,70.102064,0.807543,1.821,0,echo
500,0.006,-5.057241,79.329607,2.837858,1.821,21,direct
501,0.006,-5.057241,79.329607,2.837858,1.821,21,direct
502,0.006,-5.141267,96.541847,2.846838,1.821,21,echo
503,0.006,-5.141267,96.541847,2.846838,1.821,21,echo
504,0.006,-84.019599,66.026791,0.992514,1.821,0,echo
505,0.006,-84.019599,66.026791,0.992514,1.821,0,echo
506,0.008,3.335100,72.752385,3.087085,1.821,21,echo
507,0.008,3.335100,72.752385,3.087085,1.821,21,echo
508,0.008,-66.667586,61.156781,1.345308,1.821,0,echo
509,0.008,-66.667586,61.156781,1.345308,1.821,0,echo
510,0.009,-114.508207,60.088588,0.807185,1.821,21,echo
511,0.009,-114.508207,60.088588,0.807185,1.821,21,echo
512,0.010,10.459553,64.944619,3.384532,1.821,21,echo
513,0.010,10.459553,64.944619,3.384532,1.821,21,echo

In [30]:

grouby_call_time = new_df.groupby("bat_last_call_time")
#first call
df = grouby_call_time.get_group(2.021)
df[["delta_t", "theta", "all_spl_values", "distance_from_bat", "bat_last_call_time", "emitter_id", "type"]]

,delta_t,theta,all_spl_values,distance_from_bat,bat_last_call_time,emitter_id,type
546,0.002,71.125063,66.111128,9.239444,2.021,4,direct
547,0.002,71.125063,66.111128,9.239444,2.021,4,direct
548,0.002,58.627322,63.271680,9.068422,2.021,6,direct
549,0.002,58.627322,63.271680,9.068422,2.021,6,direct
550,0.002,71.113230,89.140393,9.249158,2.021,4,echo
551,0.002,71.113230,89.140393,9.249158,2.021,4,echo
552,0.002,58.628819,87.795548,9.078320,2.021,6,echo
553,0.002,58.628819,87.795548,9.078320,2.021,6,echo
554,0.003,36.520568,71.213111,5.531599,2.021,17,direct
555,0.003,36.520568,71.213111,5.531599,2.021,17,direct
556,0.003,36.426582,93.622622,5.535551,2.021,17,echo
557,0.003,36.426582,93.622622,5.535551,2.021,17,echo
558,0.005,38.357935,70.294914,5.993808,2.021,17,echo
559,0.005,38.357935,70.294914,5.993808,2.021,17,echo
560,0.007,-4.052587,80.676100,2.443538,2.021,21,direct
561,0.007,-4.052587,80.676100,2.443538,2.021,21,direct
562,0.007,-4.153787,97.921245,2.452444,2.021,21,echo
563,0.007,-4.153787,97.921245,2.452444,2.021,21,echo
564,0.009,40.025056,63.019983,6.456351,2.021,17,echo
565,0.009,40.025056,63.019983,6.456351,2.021,17,echo
566,0.009,5.410789,74.122134,2.704085,2.021,21,echo
567,0.009,5.410789,74.122134,2.704085,2.021,21,echo
568,0.009,-15.554642,60.559372,2.277552,2.021,21,echo
569,0.009,-15.554642,60.559372,2.277552,2.021,21,echo
570,0.011,13.168434,66.147724,3.019432,2.021,21,echo
571,0.011,13.168434,66.147724,3.019432,2.021,21,echo